"""
resume_generator.py — builds a job-tailored, ATS-friendly LaTeX resume.

Triggered by the dashboard's /api/resume/gen when the user clicks the
"LaTeX resume" button on a flashcard. Pipeline:

  1. desc_snippet() — best-effort HTTP fetch of the posting page for a
     description snippet (boards are usually JS/bot-walled; failures are
     silent and the resume is still tailored from the role title + skills).
  2. build_resume() — emits a .tex document using the user's canonical ATS
     template (see resume_data.py + ATS_TEMPLATE below): 10pt article,
     standard \\section* headings, single column, no tables — the layout ATS
     parsers read cleanly. Only the Objective and the Technical-Skills
     ordering are tailored to the specific posting.
  3. tex_to_html() — converts that same .tex into a standalone HTML preview
     so the browser can show it immediately (no TeX installation required).

The produced .tex compiles with a plain pdflatex install (no extra classes).
Everything that comes from the job boards (titles with emoji or rupee signs,
descriptions, URLs) is ascii-folded and LaTeX-escaped before it enters the
document, so the file also compiles as-is when pasted into Overleaf. The
GitHub link in the header is taken from the resume (or a user-supplied URL)
instead of a hardcoded copy.
"""

import re
import html as html_mod
import unicodedata

import requests

import resume_data

# Browser-ish UA so best-effort description fetches stand a chance of
# being served server-rendered HTML instead of a CAPTCHA page.
_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}

_EMAIL_RE = re.compile(r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}")
_PHONE_RE = re.compile(r"(\+?\d[\d\s().\-]{7,}\d)")
_LOCATION_HINT_RE = re.compile(r"hyderabad|bangalore|bengaluru|mumbai|pune|"
                               r"delhi|chennai|kolkata|india", re.I)
_SKIP_HEADER_RE = re.compile(r"^(resume|cv|curriculum|name|profile|contact|"
                             r"email|phone|address|education|experience|"
                             r"skills|objective|summary|linkedin|github)\b",
                             re.I)


# Raw ATS template. Tokens like @ROLE@ are replaced at build time; the many
# backslashes are intentional (this is LaTeX, kept in a raw string).
ATS_TEMPLATE = r"""% -------------------------------------------------------------
% Tailored \LaTeX\ resume -- generated by JobScope
%   Role: @ROLE@  |  Company: @COMPANY@  |  Source: @SOURCE@
%   Link:  @LINK@
% Generated: \today.  Compiles with plain pdflatex.
% ATS-friendly: 10pt article, standard \section* headings, single column.
% -------------------------------------------------------------
\documentclass[10pt,a4paper]{article}

\usepackage[top=0.3in, bottom=0.3in, left=0.55in, right=0.55in]{geometry}
\usepackage{titlesec}
\usepackage{enumitem}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage[T1]{fontenc}

\definecolor{accent}{HTML}{1F4E79}

\hypersetup{colorlinks=true, urlcolor=accent, linkcolor=accent}

\pagestyle{empty}

\titleformat{\section}{\large\bfseries\color{accent}}{}{0em}{}[\vspace{1pt}\titlerule\vspace{2pt}]
\titlespacing{\section}{0pt}{4pt}{2pt}

\setlist[itemize]{leftmargin=14pt, itemsep=0pt, topsep=1pt, parsep=0pt}

\newcommand{\heading}[4]{%
  \textbf{#1} \hfill \textbf{#2}\\
  \textit{#3} \hfill \textit{#4}\\[0.5pt]
}

\newcommand{\subheading}[2]{%
  \textbf{#1} \hfill #2\\[0pt]
}

\begin{document}

% ---------- HEADER ----------
\begin{center}
  {\Huge \textbf{@NAME@}}\\[6pt]
  @CONTACT@ \\[3pt]
  @LINKS@
\end{center}

\vspace{-12pt}

% ---------- OBJECTIVE (tailored to this job) ----------
\section*{Objective}
@OBJECTIVE@

% ---------- TECHNICAL SKILLS (reordered to match the posting) ----------
\section*{Technical Skills}
\begin{itemize}
@SKILLS@\end{itemize}

% ---------- EXPERIENCE ----------
\section*{Experience}
@EXPERIENCE@
% ---------- PROJECTS ----------
\section*{Projects}
@PROJECTS@
% ---------- EDUCATION ----------
\section*{Education}
@EDUCATION@
@EDUCATION_EXTRA@
% ---------- CERTIFICATIONS ----------
\section*{Certifications}
\begin{itemize}
@CERTIFICATIONS@\end{itemize}

\vspace{2pt}
\noindent\textbf{\color{accent}Languages:} \, @LANGUAGES@

\end{document}
"""


def _lx(text: str) -> str:
    r"""Escape LaTeX special chars so arbitrary CV/job text can't break the
    generated document (common gotcha: %, &, $, #, _, braces, ~, ^, \)."""
    table = {
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}", "\\": r"\textbackslash{}",
    }
    return "".join(table.get(ch, ch) for ch in str(text))


def _lx_url(s: str) -> str:
    """Escape a URL for a \\href{...} argument. pdflatex chokes on literal #, %
    and & inside macro arguments even for hyperref — those must be escaped."""
    return (str(s).strip()
            .replace("\\", "/")
            .replace("{", r"\{").replace("}", r"\}")
            .replace("%", r"\%").replace("#", r"\#")
            .replace("&", r"\&").replace("_", r"\_")
            .replace("~", r"\~").replace("^", r"\^"))


def _ascii_fold(text: str) -> str:
    """Make arbitrary job/board text compile-safe for pdflatex.

    Overleaf's default engine (pdflatex + utf8 inputenc) errors on characters
    it has no mapping for — emoji (LinkedIn titles carry \U0001F30E globes),
    the Indian rupee sign (\u20B9 from Indeed salaries), non-Latin scripts,
    en/em dashes, etc. Unicode normalize, map the common symbols we actually
    see, then drop whatever still isn't ASCII."""
    t = str(text)
    for src, dst in (("\u20b9", "Rs. "), ("\u20ac", "EUR "), ("\u00a3", "GBP "),
                     ("\u00a5", "JPY "), ("\u00b0", "deg"), ("\u2013", "-"),
                     ("\u2014", "-"), ("\u00d7", "x"), ("\ufeff", ""),
                     ("\u2605", "*"), ("\u2606", "*"), ("\u2022", "-")):
        t = t.replace(src, dst)
    t = unicodedata.normalize("NFKD", t)
    t = t.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[\x00-\x1f\x7f]", " ", t)


def _normalize_url(url: str) -> str:
    """Clean a user-supplied link: strip, drop protocol-less form's whitespace,
    add https:// when missing, killing trailing junk."""
    u = (url or "").strip().strip("\"'<>")
    if not u:
        return ""
    if not re.match(r"^[a-z][a-z0-9+.-]*://", u, re.I):
        u = "https://" + u
    return u


_GITHUB_RE = re.compile(r"https?://(?:www\.)?github\.com/([A-Za-z0-9_.-]+)", re.I)


def _find_github(text: str) -> str:
    """Pull the first GitHub URL out of a resume's plain text ('' if none)."""
    m = _GITHUB_RE.search(text or "")
    return m.group(0) if m else ""


def extract_contact(text: str) -> dict:
    """Pull name / email / phone / location out of the raw CV text.

    Used to override the canonical header when an uploaded CV differs from
    resume_data.py. Best-effort heuristics only."""
    email, phone, location, name = "", "", "", ""
    m = _EMAIL_RE.search(text)
    if m:
        email = m.group(0)
    m = _PHONE_RE.search(text)
    if m:
        phone = m.group(1).strip()
    for line in text.splitlines():
        s = line.strip()
        if not s or len(s) > 70:
            continue
        low = s.lower()
        if "@" in s or _PHONE_RE.search(s) or _SKIP_HEADER_RE.match(s):
            continue
        if re.match(r"^[A-Z][A-Za-z' .\-]{2,60}$", s):
            name = s
            break
    for line in text.splitlines():
        s = line.strip()
        if _LOCATION_HINT_RE.search(s.lower()) and len(s) <= 60:
            location = s
            break
    return {"name": name, "email": email, "phone": phone, "location": location}


def desc_snippet(url: str, limit: int = 900, timeout: int = 8) -> str:
    """Best-effort fetch of the posting page to get a description snippet.

    Most boards answer 403/CAPTCHA from plain HTTP; on any failure we return
    '' and the resume is still built from the (title + company + skills)."""
    if not url or not url.startswith(("http://", "https://")):
        return ""
    try:
        resp = requests.get(url, headers=_HEADERS, timeout=timeout)
        resp.raise_for_status()
        doc = resp.text
        # Indeed (and some boards) server-render the description in a
        # dedicated element — grab it first when present.
        m = re.search(r'(?:id|data-testid)="jobDescriptionText"[^>]*>(.*?)</div>',
                      doc, re.S | re.I)
        sentence = m.group(1) if m else doc
        # strip scripts/styles, then tags, then collapse whitespace
        sentence = re.sub(r"<(script|style|noscript)[^>]*>.*?</\1>", " ",
                          sentence, flags=re.S | re.I)
        sentence = re.sub(r"<li[^>]*>", "\n", sentence)
        sentence = re.sub(r"<[^>]+>", " ", sentence)
        sentence = html_mod.unescape(sentence)
        sentence = re.sub(r"\s+", " ", sentence).strip()
        return sentence[:limit]
    except Exception:
        return ""


def _rank_skills(job_text: str) -> tuple[list, list]:
    """Order resume_data.SKILLS so the groups the posting mentions come
    first, and return the matched keyword list (both sorted by relevance).

    job_text = (description + role + company).lower(); a plain keyword count
    keeps it deterministic and cheap."""
    hay = (job_text or "").lower()
    ranked = sorted(resume_data.SKILLS,
                    key=lambda g: -sum(hay.count(k) for k in g[2]))
    matched = [k for g in resume_data.SKILLS for k in g[2] if k in hay]
    # unique, most-mentioned first
    seen, uniq = set(), []
    for k in sorted(matched, key=lambda k: -hay.count(k)):
        if k not in seen:
            seen.add(k)
            uniq.append(k)
    return ranked, uniq


def build_resume(cfg, job: dict, desc: str = "", github_url: str = "") -> tuple[str, str]:
    """Assemble the tailored .tex document.

    Returns (latex_source, suggested_filename). job carries the flashcard
    fields (title/company/location/link/source). If desc is '' the objective
    leans on the role title + the canonical skill list instead.

    github_url is the header link for the GitHub entry: explicit argument >
    agent config > found inside the resume text > the canonical default. An
    empty override keeps whatever the resume/canonical data held. Everything
    embedded into the .tex is ascii-folded so the doc compiles on Overleaf's
    plain pdflatex even when a board's title contains emoji/rupee signs."""
    role = _ascii_fold((job.get("title") or cfg.target_role or "the role").strip())
    company = _ascii_fold((job.get("company") or "").strip())
    desc = _ascii_fold(desc)

    job_text = f"{desc} {role} {company} {cfg.resume_text or ''}"
    ranked_skills, matched = _rank_skills(job_text)

    # Header contact + links (canonical, optionally overridden by the CV).
    contact = extract_contact(cfg.resume_text or "")
    name = _ascii_fold(contact["name"] or resume_data.NAME)
    email = contact["email"] or resume_data.EMAIL
    phone = contact["phone"] or resume_data.PHONE
    location = _ascii_fold(contact["location"] or resume_data.LOCATION)

    contact_line = " \\quad $\\vert$ \\quad ".join(
        p for p in (phone,
                    f"\\href{{mailto:{_lx_url(email)}}}{{{_lx(email)}}}",
                    _lx(location)) if p)

    links = dict(resume_data.LINKS)
    gh = _normalize_url(github_url or getattr(cfg, "github_url", "")
                        or _find_github(cfg.resume_text or ""))
    if gh:
        links["github"] = gh
    link_items = []
    for url in links.values():
        if not url:
            continue
        display = _ascii_fold(url.split("//", 1)[-1].rstrip("/"))
        link_items.append(f"\\href{{{_lx_url(url)}}}{{{display}}}")
    links_line = " \\quad $\\vert$ \\quad ".join(link_items)

    # Objective: name the posting, map in the strongest matched skills.
    skills_intro = (", ".join(matched[:6])
                    if matched else "Python, Django, Flask, and REST API design")
    obj = (f"Computer Science graduate with hands-on development experience in "
           f"\\textbf{{{_lx(skills_intro)}}}, backed by SQL/NoSQL databases "
           f"(\\textbf{{MySQL, MongoDB, SQLite}}) and AWS cloud deployment. "
           f"Currently building AI-integrated backend systems as an AI/ML "
           f"Engineer Intern, seeking the \\textbf{{{_lx(role)}}} role at "
           f"\\textbf{{{_lx(company) if company else 'a remote-first company'}}} "
           f"to apply backend, cloud, and project-delivery skills.")
    if desc:
        obj += r" \\[2pt] \textit{Role focus from the posting:} " + _lx(desc[:220])

    # Technical Skills — canonical groups, reordered by posting relevance.
    skill_tex = "".join(
        f"  \\item \\textbf{{{_lx(g[0])}:}} {_lx(g[1])}\n" for g in ranked_skills)

    # Experience / Projects / Education / Certifications (canonical content).
    exp_blocks = []
    for title, dates, org, loc, bullets in resume_data.EXPERIENCE:
        head = f"\\heading{{{_lx(title)}}}{{{_lx(dates)}}}{{{_lx(org)}}}{{{_lx(loc)}}}"
        items = "".join(f"  \\item {_lx(b)}\n" for b in bullets)
        exp_blocks.append(f"{head}\n\\begin{{itemize}}\n{items}\\end{{itemize}}\n")
    proj_blocks = []
    for pname, meta, bullets in resume_data.PROJECTS:
        head = f"\\subheading{{{_lx(pname)}}}{{{_lx(meta)}}}"
        items = "".join(f"  \\item {_lx(b)}\n" for b in bullets)
        proj_blocks.append(f"{head}\n\\begin{{itemize}}\n{items}\\end{{itemize}}\n")
    edu_blocks = [
        f"\\heading{{{_lx(t)}}}{{{_lx(d)}}}{{{_lx(o)}}}{{{_lx(l)}}}"
        for t, d, o, l in resume_data.EDUCATION
    ]
    edu_extra = (f"\\subheading{{{_lx(resume_data.EDUCATION_EXTRA[0])}}}"
                 f"{{{_lx(resume_data.EDUCATION_EXTRA[1])}}}"
                 if resume_data.EDUCATION_EXTRA else "")
    cert_tex = "".join(
        f"  \\item {_lx(c)}\n" for c in resume_data.CERTIFICATIONS)

    tex = (ATS_TEMPLATE
           .replace("@NAME@", _lx(name))
           .replace("@CONTACT@", contact_line)
           .replace("@LINKS@", links_line)
           .replace("@OBJECTIVE@", obj)
           .replace("@SKILLS@", skill_tex)
           .replace("@EXPERIENCE@", "\n".join(exp_blocks))
           .replace("@PROJECTS@", "\n".join(proj_blocks))
           .replace("@EDUCATION@", "\n\n".join(edu_blocks))
           .replace("@EDUCATION_EXTRA@", edu_extra)
           .replace("@CERTIFICATIONS@", cert_tex)
           .replace("@LANGUAGES@", resume_data.LANGUAGES)
           .replace("@ROLE@", _lx(role))
           .replace("@COMPANY@", _lx(company) or "-")
           .replace("@SOURCE@", _lx(job.get("source") or "job board"))
           .replace("@LINK@", _lx(job.get("link") or "")))

    slug = re.sub(r"[^a-z0-9]+", "_", f"{company} {role}".lower()).strip("_") or "resume"
    return tex, f"Resume_{slug[:60]}.tex"


def tex_to_html(tex: str) -> str:
    """Convert the JobScope-generated .tex into a standalone HTML preview.

    Consumes the *known macro set* the template emits (\\heading, \\subheading,
    \\section*, itemize, \\textbf/\\textit/\\href) with careful ordering —
    high-level macros first so their internals never leak into the output.

    The template's own % comment lines are dropped entirely, and any escape
    the shorter _lx set produced (including \\{ / \\}) is un-escaped, so a
    user never sees raw LaTeX ("bits of code") in the preview."""
    h = tex.split("\\begin{document}")[-1].split("\\end{document}")[0]

    # 0) template comments out of the preview before anything else (% lines)
    h = re.sub(r"(?m)^[ \t]*%.*$", "", h)

    # 1) name block + section macro blocks (consume whole args)
    h = re.sub(r"\{\\Huge\s*\\textbf\{([^}]*)\}\}",
               r'<div class="rh-name">\1</div>', h)
    h = re.sub(r"\\heading\{([^}]*)\}\{([^}]*)\}\{([^}]*)\}\{([^}]*)\}",
               r'<div class="rh-h"><div class="rh-row"><strong>\1</strong>'
               r'<span class="rh-r">\2</span></div><div class="rh-row">'
               r'<em>\3</em><span class="rh-r">\4</span></div></div>', h)
    h = re.sub(r"\\subheading\{([^}]*)\}\{([^}]*)\}",
               r'<div class="rh-h"><div class="rh-row"><strong>\1</strong>'
               r'<span class="rh-r">\2</span></div></div>', h)
    h = re.sub(r"\\section\*\{([^}]*)\}", r"<h2>\1</h2>", h)

    # 2) inline markup
    h = re.sub(r"\\color\{[^}]*\}", "", h)
    h = re.sub(r"\\textbf\{([^}]*)\}", r"<strong>\1</strong>", h)
    h = re.sub(r"\\textit\{([^}]*)\}", r"<em>\1</em>", h)
    h = re.sub(r"\\href\{([^}]*)\}\{([^}]*)\}",
               r'<a href="\1" target="_blank" rel="noopener">\2</a>', h)
    h = re.sub(r"\\texttt\{([^}]*)\}", r"<code>\1</code>", h)

    # 3) lists + layout containers
    h = re.sub(r"\\begin\{itemize\}", "<ul>", h)
    h = re.sub(r"\\end\{itemize\}", "</ul>", h)
    h = re.sub(r"\\item\s+", "<li>", h)
    h = re.sub(r"\\begin\{center\}", "<div class='rh-center'>", h)
    h = re.sub(r"\\end\{center\}", "</div>", h)

    # 4) whitespace + line breaks
    h = re.sub(r"\\\\\[[0-9]+pt\]", "<br>", h)
    h = re.sub(r"\\\\", "<br>", h)
    h = re.sub(r"\\(?:vspace|hspace)\*?\{[^}]*\}", "", h)
    h = h.replace("\\noindent", "").replace("\\quad", "    ").replace("\\hfill", " ")
    h = h.replace("\\,", " ").replace("$\\vert$", "|")

    # 5) escaped characters
    h = h.replace(r"\%", "%").replace(r"\&", "&").replace(r"\$", "$")
    h = h.replace(r"\#", "#").replace(r"\_", "_")
    h = h.replace("\\textasciitilde", "~").replace("\\textasciicircum", "^")
    h = h.replace(r"\textbackslash", "\\").replace(r"\cdot", "\u00b7")
    h = h.replace(r"\{", "{").replace(r"\}", "}")

    # 6) purge any remaining command, brace-escape leftover, or stray brace
    h = re.sub(r"\\[a-zA-Z]+", "", h)
    h = h.replace("{", "").replace("}", "")
    h = re.sub(r"\\+", " ", h)       # any last lone backslashes -> plain space
    h = re.sub(r"(\s*\n){3,}", "\n", h)
    return h.strip()


if __name__ == "__main__":
    # offline self-test: build + preview (no network fetch)
    from agent import AgentConfig
    cfg = AgentConfig(target_role="Junior Data Analyst / entry-level, 0-2 years experience",
                      skills=["python", "django", "rest api"])
    job = {"title": "Junior Python Developer", "company": "Stripe Inc",
           "location": "Remote", "link": "https://www.indeed.com/x",
           "source": "Indeed"}
    tex, fname = build_resume(cfg, job,
                              desc="Django, Flask, REST API, MongoDB, AWS "
                                   "cloud deployment, Python")
    print("FILENAME:", fname)
    print(tex[:800])
    print("---- HTML PREVIEW ----")
    print(tex_to_html(tex)[:600])